### DISCUSSION TITLE
Alpine Linux

### DISCUSSION THREAD

**Discussion by rogerxu** [rogerxu/rogerxu.github.io#285] [Ideas]
[Alpine User Handbook](https://docs.alpinelinux.org/user-handbook/0.1a/index.html)

**Comment by rogerxu** [comment]
## Package Manager

[Working with the Alpine Package Keeper (apk)](https://docs.alpinelinux.org/user-handbook/0.1a/Working/apk.html)

### Mirrors

`/etc/apk/repositories`

```
https://mirrors.ustc.edu.cn/alpine/v3.19/main
https://mirrors.ustc.edu.cn/alpine/v3.19/community
```

```sh
sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
```

```vim
:%s/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g
```

### Usage

Search

```sh
apk search helix
```

Info

```sh
apk info helix
```

Install

```sh
apk add helix
```

Upgrade

```sh
apk update
apk upgrade
```

Remove

```sh
apk del helix
```

**Comment by rogerxu** [comment]
## Configuration

```sh
setup-alpine
```

**Comment by rogerxu** [comment]
## OpenRC

[Working with OpenRC](https://docs.alpinelinux.org/user-handbook/0.1a/Working/openrc.html)

OpenRC is the init system used in alpine.


### Usage

Runtime Service

```bash
rc-service sshd start
rc-service sshd status
rc-service sshd stop
```

On-Boot Service

```bash
rc-update show -v

# add to the default runlevel
rc-update add sshd default

# add to the cuurent runlevel
rc-update add sshd

# remove from the current runlevel
rc-update delete sshd

# remove from all runlevels
rc-update delete sshd -a
```

System Status

```bash
rc-status

# List all the available runlevels
rc-status -l

# List all the crashed services
rc-status -c

# List all the services
rc-status -s
```

**Comment by rogerxu** [comment]
## Proxy

### mihomo

[mihomo](https://github.com/MetaCubeX/mihomo)

#### Install

```bash
wget https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-amd64-v1.18.9.gz
```

```bash
gzip -d mihomo-linux-amd64-v1.18.9.gz
mv mihomo-linux-amd64-v1.18.9 /usr/local/bin/mihomo
chmod +x /usr/local/bin/mihomo
```

#### Configuration

https://wiki.metacubex.one/config/

```bash
mkdir /etc/mihomo
```

```bash
wget -O /etc/mihomo/config.yaml https://mirror.ghproxy.com/https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml
```

Example: https://github.com/MetaCubeX/mihomo/blob/Meta/docs/config.yaml

`/etc/mihomo/config.yaml`

```yaml
allow-lan: true
bind-address: "*"
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
external-controller-tls: 0.0.0.0:9443 # RESTful API HTTPS 监听地址，需要配置 tls 部分配置文件
secret: "123456" # `Authorization:Bearer ${secret}`

# RESTful API CORS标头配置
external-controller-cors:
  allow-origins:
    - "*"
  allow-private-network: true
```

#### Service Daemon

[OpenRC Service Script Writing Guide](https://github.com/OpenRC/openrc/blob/master/service-script-guide.md)

`/etc/init.d/mihomo`

```bash
#!/sbin/openrc-run

name="mihomo"
description="mihomo daemon, A rule-based proxy in Go."

command="/usr/local/bin/mihomo"
command_args="-d /etc/mihomo"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
    need net
    after net
}
```

```ash
chmod +x /etc/init.d/mihomo
```

Start service

```ash
rc-service mihomo start
rc-udpate add mihomo
```

#### Web Client

[Metacubexd](http://d.metacubex.one/)
