### ISSUE TITLE
Web Fonts

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#102]
[Web fonts - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts)

**Comment by rogerxu** [comment]
# Web Fonts

```css
@font-face {
  font-family: "Fira Code";
  src: url("font.woff") format("woff"),
       url("font.ttf") format("truetype"),
       url("font.otf") format("opentype"),
       url("font.eot") format("embedded-opentype"),
       url("font.svg") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

### Font Formats

#### TrueType

- `.ttf`
- 1999
- Apple, Microsoft

#### TrueType Open

- 1994
- Microsoft

#### OpenType

- `.otf`
- 1996
- Microsoft, Adobe
- PostScript

#### Web Open Font Format

- `.woff`
- 2009
- Mozilla. Opera, Microsoft
