### ISSUE TITLE
YAML

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#215]
[The Official YAML Web Site](http://yaml.org/)

**Comment by rogerxu** [comment]
## Collections

* Sequence - `- `
* Mapping - `: `

Sequence of Scalars

```yaml
- Apple
- Banana
- Orange
```

Mapping Scalars to Scalars

```yaml
name: Roger
gender: male
age: 31
```

Mapping Scalars to Scalars

```yaml
male:
  - Roger
  - Bob
female:
  - Amy
  - Linda
```

Sequence of Mappings

```yaml
-
  name: Roger
  gender: male
  age: 31
-
  name: Bob
  gender: male
  age: 30
```

```yaml
- name: Roger
  gender: male
  age: 31
- name: Bob
  gender: male
  age: 30
```

**Comment by rogerxu** [comment]
## Structures

### Separate document

* start - `---`
* end - `...`

### Repeat nodes

* Mark - `&<alias>`
* Reference - `*<alias>`

Node for “Sammy Sosa” appears twice in this document

```yaml
---
hr:
  - Mark McGwire
  # Following node labeled SS
  - &SS Sammy Sosa
rbi:
  - *SS # Subsequent occurrence
  - Ken Griffey
```

**Comment by rogerxu** [comment]
## Scalars

* literal style - `|` - new lines are perserved

```yaml
# ASCII Art
--- |
  \//||\/||
  // ||  ||__
```

* folded style - `>` - lines are joined by a space

```yaml
--- >
  Mark McGwire's
  year was crippled
  by a knee injury.
```

* double-quoted style - escape sequences

```yaml
unicode: "Sosa did fine.\u263A"
control: "\b1998\t1999\t2000\n"
hex esc: "\x0d\x0a is \r\n"
```

* single-quoted style - escaping is not needed

```yaml
single: '"Howdy!" he cried.'
quoted: ' # Not a ''comment''.'
tie-fighter: '|\-*-/|'
```

**Comment by rogerxu** [comment]
## Tags

### General

```yaml
null:
booleans: [ true, false ]
string: '012345'
```

### Integers

```yaml
canonical: 12345
decimal: +12345
octal: 0o14
hexadecimal: 0xC
```

### Floating Point

```yaml
canonical: 1.23015e+3
exponential: 12.3015e+02
fixed: 1230.15
negative infinity: -.inf
not a number: .NaN
```

### Timestamps

```yaml
canonical: 2001-12-15T02:59:43.1Z
iso8601: 2001-12-14t21:59:43.10-05:00
spaced: 2001-12-14 21:59:43.10 -5
date: 2002-12-14
```
