### ISSUE TITLE
CSS Variables

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#269]
[CSS 变量教程 - 阮一峰的网络日志 (ruanyifeng.com)](https://www.ruanyifeng.com/blog/2017/05/css-variables.html)

**Comment by rogerxu** [comment]
## Syntax

**Comment by rogerxu** [comment]
## Functions

### `val()`

```css
a {
  color: var(--foo);
}

a {
  color: var(--foo, #fff);
}
```

**Comment by rogerxu** [comment]
## Variable Types

### String

### Numeric

**Comment by rogerxu** [comment]
## Scope

```css
:root {
  --main-color: #fff;
}

p {
  --main-color: #000;
}
```
