### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#37]
[Sass: Sass Basics](http://sass-lang.com/guide)

**Comment by rogerxu** [comment]
## CSS Extensions

### Nesting

```scss
// nesting
nav {
  ul {
    margin: 0;
    padding: 0;
    list-style: none;
  }
  
  li {
    display: inline-block;
  }
  
  a {
    display: block;
    padding: 6px 12px;
    text-decoration: none;
  }
}
```

### Referencing Parent Selectors: `&`

```scss
a {
  text-decoration: none;
  &:hover {
    text-decoration: underline;
  }
}
```

### Nested Properties

```scss
.highlight {
  font: {
    family: Arial;
    size: 30em;
    weight: bold;
  }
}
```

**Comment by rogerxu** [comment]
# Nesting

**Comment by rogerxu** [comment]
## @-Rules and Directives

### `@import`

All imported SCSS files will be merged together into a single CSS output file.

```scss
@import 'foo', 'bar';
@import 'http://foo.com/bar';
@import url("http://foo.com/#{$bar}"); // only for CSS imports
```

### Partials

A partial is simply a Sass file named with a leading underscore.

`_colors.scss` it tells Sass not to compile it to a normal CSS file.

```scss
@import 'colors';
```

### Nested `@import`

```scss
#main {
  @import 'example';
}
```

### `@media`

```scss
.sidebar {
  width: 300px;
  @media screen and (orientation: landscape) {
    width: 500px;
  }
}
```

### `@extend`

```scss
.error {
  border: 1px solid #f00;
  background-color: #fdd;
}

.serious-error {
  @extend .error;
  border-width: 3px;
}
```

### `@at-root`

### `@debug`, `@warn`, `@error`

It prints the value of a SassScript expression to the standard error output stream.

```scss
@debug 10em + 12em;
```

**Comment by rogerxu** [comment]
## Extend/Inheritance

Placeholder Selectors: `%foo`

```scss
// This CSS won't print because %equal-heights is never extended.
%equal-heights {
  display: flex;
  flex-wrap: wrap;
}

// This CSS will print because %message-shared is extended.
%message-shared {
  border: 1px solid #ccc;
  padding: 10px;
  color: #333;
}

.message {
  @extend %message-shared;
}

.success {
  @extend %message-shared;
  border-color: green;
}

.error {
  @extend %message-shared;
  border-color: red;
}

.warning {
  @extend %message-shared;
  border-color: yellow;
}
```

**Comment by rogerxu** [comment]
# Extend/Inheritance

**Comment by rogerxu** [comment]
# Operators

**Comment by rogerxu** [comment]
# Referencing Parent Selectors: `&`

**Comment by rogerxu** [comment]
# Comments

`/* */` and `//`

**Comment by rogerxu** [comment]
# Output Style

## `:nested`

## `:expanded`

## `:compact`

## `:compressed`

**Comment by rogerxu** [comment]
## Variables

```scss
$font-stack: "Fira Code", Consolas;

body {
  font: 100% $font-stack;
}
```
