### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#38]
[PostCSS - a tool for transforming CSS with JavaScript](http://postcss.org/)

[postcss-cssnext features](http://cssnext.io/features/)

**Comment by rogerxu** [comment]
## cssnext features

### Automatic Vendor Prefixes

`autoprefixer`

### Custom Properties & `var()`

Similar to Sass variables.

```css
:root {
  --mainColor: red;
}

a {
  color: var(--mainColor);
}
```

### Custom Properties Set & `@apply`
