### ISSUE TITLE
CSS Floats

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#54]
[Floats - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Floats)

[All About Floats | CSS-Tricks](https://css-tricks.com/all-about-floats/)

[经验分享：CSS浮动(float,clear)通俗讲解 - 杨元 - 博客园](http://www.cnblogs.com/iyangyuan/archive/2013/03/27/2983813.html)

**Comment by rogerxu** [comment]
## float

In web design, page elements with the CSS float property applied to them are just like the images in the print layout where the text flows around them. Floated elements *remain a part of the flow of the web page*.

![image](https://user-images.githubusercontent.com/1114360/40277529-d7142bf0-5c52-11e8-8098-f33528561df2.png)

**Comment by rogerxu** [comment]
## clear

An element that has the clear property set on it will not move up adjacent to the float like the float desires, but will move itself down past the float.

https://css-tricks.com/wp-content/csstricks-uploads/unclearedfooter.png
![image](https://user-images.githubusercontent.com/1114360/40277537-04be1124-5c53-11e8-92e1-074e66f50973.png)

```css
#footer {
  clear: both;			
}
```

https://css-tricks.com/wp-content/csstricks-uploads/clearedfooter.png
![image](https://user-images.githubusercontent.com/1114360/40277559-41dde5f2-5c53-11e8-976e-c7376e059c7f.png)

```css
.container::after { 
   content: "."; 
   visibility: hidden; 
   display: block; 
   height: 0; 
   clear: both;
}
```
