### ISSUE TITLE
CSS Position

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#60]
[Positioning - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning)

**Comment by rogerxu** [comment]
## Vertical Align

[Centering in CSS: A Complete Guide | CSS-Tricks](https://css-tricks.com/centering-css-complete-guide/)

[Understanding vertical-align, or "How (Not) To Vertically Center Content"](http://phrogz.net/css/vertical-align/index.html)

### `vertical-align` in table cells

```html
<td style="vertical-align:middle"> ... </td>
```

### `vertical-align` on inline elements

```css
img.baseline {
  vertical-align: baseline;
}

img.middle {
  vertical-align: middle;
}

img.bottom {
  vertical-align: text-bottom;
}
```
