### ISSUE TITLE
CSS Transitions

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#63]
[transition | CSS-Tricks](https://css-tricks.com/almanac/properties/t/transition/)

**Comment by rogerxu** [comment]
# CSS Transitions

```css
div {
  transition: background-color 0.5s ease;
  background-color: red;
}
div:hover {
  background-color: green;
}
```
