### ISSUE TITLE
CSS Animations

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#64]
[animation | CSS-Tricks](https://css-tricks.com/almanac/properties/a/animation/)

**Comment by rogerxu** [comment]
[CSS 对比 JavaScript 动画  |  Web  |  Google Developers](https://developers.google.com/web/fundamentals/design-and-ui/animations/css-vs-javascript)

**Comment by rogerxu** [comment]
# CSS Animations

```css
.element {
  animation: pulse 5s infinite;
}

@keyframes pulse {
  0% {
    background-color: #001F3F;
  }
  100% {
    background-color: #FF4136;
  }
}
```
