### ISSUE TITLE
CSS Box Model

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#65]
[Introduction to the CSS box model - CSS | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model)

[The box model - Learn web development | MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Box_model)

**Comment by rogerxu** [comment]
Default is `content-box`

```css
* {
  box-sizing: content-box;
}
```

You can change to `border-box`.

```css
* {
  box-sizing: border-box;
}
```
